<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-L47TV1TH" failures="1" tests="9" name="com.TestNg.org.TestNg.Priorrity" time="0.013" errors="0" timestamp="2021-04-04T19:03:32 IST" skipped="3">
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="logOut" time="0.000"/>
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="browserLaunch" time="0.000">
    <failure message="expected [arsh] but found [arsa]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [arsh] but found [arsa]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.TestNg.org.TestNg.Priorrity.browserLaunch(Priorrity.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- browserLaunch -->
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="browserLaunch" time="0.002">
    <skipped/>
  </testcase> <!-- browserLaunch -->
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="browserLaunch" time="0.000">
    <skipped/>
  </testcase> <!-- browserLaunch -->
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="SearchMobile" time="0.001"/>
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="Url" time="0.001"/>
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="login" time="0.001"/>
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="Payment" time="0.007"/>
  <testcase classname="com.TestNg.org.TestNg.Priorrity" name="browserLaunch" time="0.001">
    <skipped/>
  </testcase> <!-- browserLaunch -->
</testsuite> <!-- com.TestNg.org.TestNg.Priorrity -->
